### ISSUE TITLE
API 입출력 테스트

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#24]
필요한 최소한의 API 기능을 확인하고 테스트 진행
클라이언트에 노출할 API 요청, 응답에 대한 스펙 구성  
내부 비지니스 로직을 별로로 진행
## Todo
* [x] 특정 회원의 테이블 스키마 목록 조회 (페이징 고려)
* [x] 특정 회원의 테이블 스키마 단건 조회
* [x] 특정 회원의 테이블 스키마 저장, 수정, 삭제
* [x] 스키마 필드 출력 (csv, json, tsv, sql)
* [x] 회원 정보 조회
* [x] 메인 페이지 설정
