### ISSUE TITLE
뷰 만들기 : 메인 페이지

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#32]
테스트 데이터 생성기 서비스의 메인 페이지는 바로 테이블 스키마 뷰를 제공
## Todo
* [x] 헤더 GNB 구성
* [x] 테이블 스키마 페이지에서 테이블 스키마 폼 제공
* [x] 메인 페이지는 로그인 유무와 상관없이 테이블 스키마 작성 페이지 반환
* [x] 푸터는 간단한 기본정보만 표시
* [ ] #33
