### ISSUE TITLE
뷰 만들기 : 자료형 선택 화면

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#39]
Mockaroo 에서는 각 필드 자료형을 클릭할 때 팝업을 띄워주는데 (modal 형식) 이에 대한 구현을 검토

## Todo
* [x] 팝업 디자인 검토
* [x] 구현이 필요한 기능 정리
   - 자료형을 모두 보여줌
   - 자료형을 그룹별로 보여줌
   - 자료형을 검색할 수 있게 함
* [ ] 자료형 선택화면 구현 여부

**Comment by hoonseung** [comment]
검토 결과 : 모달 팝업 기능을 구현할 때 디자인이나 프론트 요소 중심으로 개발될 것으로  예상되고 러닝 커브도 있다고 생각됨 
현재 백엔드를 중심으로 코드를 작성하고 있기 때문에 해당 서비스에는 제외 하겠음
