### ISSUE TITLE
인증기능 : github OAuth 인증 구현

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#40]
인증 접근 권한 프레임워크인 OAtuh 2.0 인증을 도입함
이 서비스서는 github OAuth를 사용함
## Todo
* [x] 깃허브 OAuth  Apps 등록
* [x] 깃허브 인증 연결
* [ ] 깃허브 인증 데이터 설계
* [x] 설정 클래스 수정
* [x] 내 정보 페이지에 인증 정보 전달
