### ISSUE TITLE
로직 구현 : 스키마 데이터를 원하는 포맷으로 변환

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#50]
테스트 데이터 생성기에서 스키마 정보를 특정 파일 포맷으로 변환하는 기능을 구현

## Todo
* [x] `.csv` 포맷 변환기
* [x] `.tsv` 포맷 변환기
* [ ] `.json` 포맷 변환기
* [ ] `.sql` 포맷 변환기

**Comment by hoonseung** [comment]
`.json` , `.sql` 포맷은 별도로 추후 구현할 필요가 있음
