### ISSUE TITLE
자료형 도메인 설계

### ISSUE THREAD

**Issue by hoonseung** [hoonseung/test-data#6]
자료형을 선택하여 해당 자료형에 적절한 가짜 데이터를 생성
## Todo
* [x] 자료형 데이터 타입을 엔티티로 만들것인가 ?
* [x] 이름, 다양한 옵션들
   - 옵션이 필요없는 경우
   - 옵션을 키 밸류 형식으로 어떤 옵션이든 유연하게 받아보기
   - 시간 출력 형식
   - 일정한 규칙을 가진 고정 길이 문자열
   - 일정한 규칙을 가진 가변 길이 문자열
   - 랜덤 생성 문단
* [x] 다양한 자료형 지원
* [ ] ~~자료형은 검색하여 선택할 수 있어야 한다. (인덱스 생각)~~

**Comment by hoonseung** [comment]
가짜 데이터의 자료형 도메인은 enum으로 관리함

**Comment by hoonseung** [comment]
가짜 데이터의 자료형 검색 기능은 우선 미뤄두고 추 후에 검토
